### ISSUE TITLE
question for crypto logos

### ISSUE THREAD

**Issue by gruiny** [piotrwawrzyn/simple-arduino-crypto-display#9]
Hi 
Thx for this nice project i like it mutch. 
i would like to ad some other crypto logos but i need help to generate the bmp code 😅  i dont know how to do this 🙈  hope you can help me.

**Comment by IAmKab** [comment]
Same issue. I have tried to make a 32x32 bitmat array but it doesn't come out properly. The image is always broken on the OLED display

**Comment by gruiny** [comment]
@IAmKab i found a solution 😅 
first convert your pic to a ico 32x32 with this link Online: 
http://image.convertstandard.com/toico32x32.aspx

After take the file and convert it again online on this site:
https://www.online-utility.org/image/convert/to/XBM

Open the file with a text editor and voila you have the code to insert in the "cryptos.h" file.

**Comment by IAmKab** [comment]
> @IAmKab i found a solution 😅
> first convert your pic to a ico 32x32 with this link Online:
> http://image.convertstandard.com/toico32x32.aspx
> 
> After take the file and convert it again online on this site:
> https://www.online-utility.org/image/convert/to/XBM
> 
> Open the file with a text editor and voila you have the code to insert in the "cryptos.h" file.

Thank you! I spent hours trying different things trying to get the images to work

**Comment by stonkinator12** [comment]
Hey! when i import a new ctpro i have this eror

"too many initializers for 'char"

Can you help me ?

**Comment by piotrwawrzyn** [comment]
Hey guys, sorry for the late response, I was kind of unavailable lately.

I updated the readme file with [instructions](https://github.com/piotrwawrzyn/simple-arduino-crypto-display/blob/master/README.md#getting-bitmap-of-your-cryptos-logo) on how to get a perfect bitmap that will display nicely. It has always worked for me, it will surely work for you as well. Cheers.

**Comment by stzcze** [comment]
It works great, thank you very much for your update
